[BIP 39] Add reference implementation
bitcoin/bips pull request #1095
Opened 2021-03-31 20:02 UTC by eMaringolo

Add an existing reference implementation done in 100% Smalltalk code.

2021-04-22 22:48 UTC, luke-jr commented
@slush0 @prusnak @voisine @ebfull

2021-04-23 07:40 UTC, prusnak requested changes

2021-04-23 07:40 UTC, prusnak commented on bip-0039.mediawiki
> +* Smalltalk:
```suggestion
Smalltalk:
```

2021-05-27 12:59 UTC, eMaringolo commented
Is there anything stopping this minor change from being merged?

2021-05-27 20:47 UTC, prusnak commented
@eMaringolo I posted a suggestion above how you should fix a syntax error. Once this has been addressed I don't see any further issues.

2021-05-28 23:22 UTC, prusnak commented
ACK

2021-05-29 22:39 UTC, garkelin commented
ACK

2021-05-31 12:01 UTC, MarcoFalke commented
@luke-jr

2021-06-13 03:43 UTC, merged