Define BIP Steward Process and set Temporary Editor
bitcoin/bips pull request #1113
Opened 2021-04-26 16:45 UTC by JaimeCaring

On https://github.com/JaimeCaring/OpenBIPs/issues/2 I received feedback that a new repo was "nuclear".

Up-streaming the OpenBIPs process here. See the linked issue for motivation.

I'm happy for a non-nym editor to replace me championing this process, but I don't think anyone deserves the political and reputational loss for this necessary action.

2021-04-27 11:02 UTC, michaelfolkson commented
NACK. This seems to be being [discussed](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018866.html) on the mailing list by some of the proposed "stewards" and I don't see any reason why it won't be resolved in the usual way without getting 23 people involved. Thanks for trying to move this along but I don't think it is needed personally.

2021-04-28 13:49 UTC, prayank23 commented
NACK everything mentioned in this PR

2021-05-07 18:54 UTC, JeremyRubin commented
Concept ACK -- I don't think this is required right now, but it does seem like a decent enough path longer term for governing the BIP process... people might prefer ad hoc process, but I'm a frequent citationer of https://www.jofreeman.com/joreen/tyranny.htm, so I think defined processes end up being less corrupt and more robust than undefined.

curious what bip editor @luke-jr and editor-to-be @kallewoof  think about standardizing something similar?

2021-05-08 06:40 UTC, MarcoFalke requested changes
NACK. Please stop electing random people as "Stewards" even when they explicitly asked you not to do this: https://github.com/JaimeCaring/OpenBIPs/issues/2#issuecomment-831157867

2021-05-08 06:40 UTC, MarcoFalke commented on bip-0002.mediawiki
> +* @MarcoFalke MarcoFalke
NACK. Please stop spamming this repository and the list of people here. I am not aware that anyone in this list consents to being included here. In fact there are several that wished to be taken off the list. I can't speak for others, but I certainly don't want to be involved in this and I don't want to further my responsibilities in Bitcoin apart from quality assurance where I voluntarily provide my feedback.

2021-05-10 07:48 UTC, MarcoFalke commented
I think this can be closed?

2021-05-14 11:00 UTC, michaelfolkson commented
> I think this can be closed?

Agree that this should be closed. It is a massive proposed change to BIP processes and clearly has strong opposition from many including a number of the proposed "stewards". Those "stewards" should have given their consent prior to be included. It appears none of them were aware that they were being put forward until the PR was opened. Other than perhaps @JeremyRubin I don't see anyone else supporting it.

2021-05-17 23:08 UTC, closed without merging