Add Kalle Alm as BIP editor
bitcoin/bips pull request #1116
Opened 2021-05-07 08:22 UTC by jnewbery

Update language to clarify that there are multiple editors.

2021-05-07 08:25 UTC, MarcoFalke commented
ACK 20bda62185469fb6cf7e105e62b4fd256a987e80, assuming ACK by @kallewoof

2021-05-07 08:30 UTC, jnewbery commented
Originally proposed in Bitcoin Core irc meeting (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-338). ACKs from:

- @jnewbery (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-382)
- @MarcoFalke (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-385)
- @harding (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-581)
- @JeremyRubin (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-583)
- @meshcollider (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-590)

It was then proposed to the Bitcoin developer mailing list by @luke-jr (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018835.html). ACKs from:

- Pindar Wong (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018837.html)
- Eric Martindale (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018839.html)
- @nopara73 (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018848.html)
- @Sjors (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018865.html)
- @jamesob (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018867.html)
- @laanwj (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018866.html)
- @gmaxwell (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018869.html) (original NACK at https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018846.html presumably withdrawn)

One NACK from @jaimecaring (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018877.html) proposing instead a "stewardship committee".

2021-05-07 09:10 UTC, kallewoof reviewed
ACK sans nit

2021-05-07 09:10 UTC, kallewoof commented on bip-0002.mediawiki
> +The current BIP editor are:
```suggestion
The current BIP editors are:
```

2021-05-07 09:14 UTC, jnewbery commented on bip-0002.mediawiki
> +The current BIP editor are:
Already proving yourself as an editor! Fixed.

2021-05-07 09:20 UTC, MarcoFalke approved these changes

2021-05-07 09:22 UTC, kallewoof commented
ACK f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-05-07 10:43 UTC, nopara73 approved these changes
ACK. The generalization of the document LGTM.

2021-05-07 11:25 UTC, junderw commented
ACK

2021-05-07 12:59 UTC, michaelfolkson commented
Certainly no problem with @kallewoof being added as an additional editor. Only consideration re merging this is (imo) whether this change is included in the planned BIP 3 process [revision](https://github.com/bitcoin/bips/pull/1015) that @kallewoof has planned and whether BIP 2 should be left as is given there will likely be a number of proposed changes for BIP 3 in addition to a new BIP editor.

2021-05-07 13:22 UTC, MarcoFalke commented
I don't understand why meta process BIPs need to be assigned a new BIP number each time they are modified. This just creates confusion as to which one is the latest active one. Also, it bloats the already large repo even more with historic documents that are irrelevant to the current process. Historians can always ask the git log for previous versions.

2021-05-07 14:44 UTC, luke-jr commented
For reference: https://github.com/bitcoin/bips/wiki/BIP-Process-wishlist

2021-05-07 16:25 UTC, harding commented
ACK f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-05-07 18:46 UTC, JeremyRubin commented
ACK adding @kallewoof as noted above.

I am sympathetic to the idea that the process of becoming or un-becoming an editor should be defined 'n documented, but I think that @kallewoof and @luke-jr can propose something as opposed to the more aggressive plan/nack from @JaimeCaring. I think they shouldn't punt on doing so, however.

2021-05-13 19:17 UTC, fjahr commented
ACK f5575fb

2021-05-13 20:25 UTC, michaelfolkson commented
A judgement for the current BIP editor (@luke-jr) and the future BIP editor (@kallewoof) on if/when it is appropriate for this to be merged.

We have already had pressure for Taproot activation params to be merged (which they were), pressure for an additional BIP editor to be agreed to (which it was) and pressure for a new BIP editor to be chosen (which it was). At some point people need to step back and trust the individuals involved to move forward in their own time rather than pressuring for PR merges within a week of it being opened. Although ACKs from other reviewers are informative, in this repo ACKs generally only hold real weight re merge decisions if the ACKs are from BIP authors.

@kallewoof: If you are uncomfortable with progress as you onboard as a new BIP editor in collaboration with Luke please raise it and we can discuss how to help you. Otherwise I'd ask people to leave them to it and consider the precedent they are setting by demanding merges within certain time periods.

2021-05-14 05:05 UTC, kallewoof commented
As I noted on IRC, I'm not uncomfortable at all, and I'm grateful to John for championing this as he's done so far. I have no issues waiting for Luke to get around to merging this, but I understand people's frustration.

2021-05-14 05:12 UTC, MarcoFalke commented
> in this repo ACKs generally only hold real weight re merge decisions if the ACKs are from BIP authors.

This is not true for meta BIPs, BIP 2 says:

> A Process BIP describes a process surrounding Bitcoin, or proposes a change to (or an event in) a process. Process BIPs are like Standards Track BIPs but apply to areas other than the Bitcoin protocol itself. They may propose an implementation, but not to Bitcoin's codebase; they often require **community consensus**; unlike Informational BIPs, they are more than recommendations, and users are typically not free to ignore them. Examples include procedures, guidelines, changes to the decision-making process, and changes to the tools or environment used in Bitcoin development. Any meta-BIP is also considered a Process BIP.

2021-05-14 10:04 UTC, michaelfolkson commented
> This is not true for meta BIPs

Thanks for the correction. Then we need community consensus on potentially making multiple changes to BIP 2 or community consensus on what is included in a new BIP, BIP 3 as @kallewoof has tentatively put forward [here](https://github.com/bitcoin/bips/pull/1015).

@kallewoof: What are your thoughts on making some of these [proposed changes](https://github.com/bitcoin/bips/wiki/BIP-Process-wishlist) to the BIP process in BIP 2 versus starting afresh with a new BIP, i.e. BIP 3?

2021-05-14 10:19 UTC, MarcoFalke commented
I fail to see how my quote implies that a change that has community consensus and is ready to be merged needs to be held back and bundled with changes that don't (yet) have community consensus.

Also, the discussion seems slightly off-topic for this thread and a separate discussion might be more appropriate.

2021-05-14 10:24 UTC, michaelfolkson commented
> I fail to see how my quote implies that a change that has community consensus and is ready to be merged needs to be held back and bundled with changes that don't (yet) have community consensus.

Because once you make one change to BIP 2 you might as well make multiple. That effectively makes the BIP 2/3 decision.

> Also, the discussion seems slightly off-topic for this thread and a separate discussion might be more appropriate.

I disagree it is off-topic for previous rationale. Though I agree a separate discussion is appropriate and something I expect to happen in future when Luke, Kalle are ready to have that discussion. Rushing through merges doesn't seem like a good idea to me generally let alone when there are broader meta BIP issues to be resolved.

2021-05-14 10:46 UTC, kallewoof commented
I think updating BIP 2 to edit/add editors is a different question from modifying BIP 2, so I agree with @MarcoFalke here. Let's move the discussion of extensive/further changes to a separate thread (https://github.com/bitcoin/bips/wiki/BIP-Process-wishlist is a good starting point).

2021-05-20 08:01 UTC, NicolasDorier commented
ACK

2021-05-20 08:05 UTC, MarcoFalke commented
@luke-jr Seems ready for merge

2021-05-20 19:35 UTC, laanwj commented
ACK f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-05-20 20:23 UTC, jnewbery commented
### Summary

Proposal originally made on 22-04-2021 (**28 days ago**)

**18** ACKs

1. @jnewbery (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-382)
1. @MarcoFalke (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-385)
1. @harding (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-581)
1. @JeremyRubin (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-583)
1. @meshcollider (http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-22.html#l-590)
1. @pindarwong (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018837.html)
1. @martindale (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018839.html)
1. @nopara73 (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018848.html)
1. @Sjors (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018865.html)
1. @jamesob (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018867.html)
1. @laanwj (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018866.html)
1. @gmaxwell (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018869.html)
1. @kallewoof (https://github.com/bitcoin/bips/pull/1116#issuecomment-834204523)
1. @junderw (https://github.com/bitcoin/bips/pull/1116#issuecomment-834286038)
1. @dr-orlovsky (https://github.com/bitcoin/bips/pull/1116#pullrequestreview-654566209)
1. @fjahr (https://github.com/bitcoin/bips/pull/1116#issuecomment-840776244)
1. @NicolasDorier (https://github.com/bitcoin/bips/pull/1116#issuecomment-844835196)
1. @laanwj (https://github.com/bitcoin/bips/pull/1116#issuecomment-845419790)

2021-05-24 17:33 UTC, Rspigler commented
Concept ACK (I have not proof read the text yet)

2021-05-31 12:00 UTC, MarcoFalke commented
@luke-jr

2021-06-01 01:50 UTC, Rspigler commented
ACK commit f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-06-06 10:32 UTC, dr-orlovsky approved these changes
ACK f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-06-08 04:28 UTC, ajtowns reviewed
ACK f5575fbaacb289fda64e22ed5db9abfc1d1c6756

2021-06-11 06:08 UTC, luke-jr requested changes
Looks good for the most part.

A few nits:

2021-06-11 06:08 UTC, luke-jr commented on bip-0002.mediawiki
> +A BIP editor will not unreasonably reject a BIP.
```suggestion
The BIP editors will not unreasonably reject a BIP.
```

2021-06-11 06:08 UTC, luke-jr commented on bip-0002.mediawiki
> +If you are interested in assuming ownership of a BIP, send a message asking to take over, addressed to both the original author and a BIP editor. If the original author doesn't respond to email in a
```suggestion
If you are interested in assuming ownership of a BIP, send a message asking to take over, addressed to both the original author and the BIP editors. If the original author doesn't respond to email in a timely manner, the BIP editors will make a unilateral decision (it's not like such decisions can't be reversed :).
```

2021-06-11 06:08 UTC, luke-jr commented on bip-0002.mediawiki
> +Off-list BIP-related correspondence should be sent (or CC'd) to one of the BIP editors.
```suggestion
Off-list BIP-related correspondence should be sent (or CC'd) to the BIP editors.
```

2021-06-11 09:19 UTC, jnewbery commented
@luke-jr - I've taken your review comments.

This is ready for merge.

2021-06-11 09:46 UTC, ajtowns commented
ACK 4e53b6e6c4b279e76ccf107a5a315911466bda4b 

corrects choice of singular editor to all editors in a few places

2021-06-11 10:48 UTC, kallewoof commented
ACK, thanks for the patience everyone.

2021-06-11 10:48 UTC, merged