Enable secure protocol for all translations
bitcoin/bips pull request #1240
Opened 2021-11-23 16:17 UTC by suriyaa

2021-12-11 21:12 UTC, katesalazar requested changes
Broken links are replaced with broken links,
causing history noise for no benefit.

2021-12-11 21:12 UTC, katesalazar commented on bip-0016.mediawiki
> +These new rules should only be applied when validating transactions in blocks with timestamps >= 1333238400 (Apr 1 2012) <ref>[https://github.com/bitcoin/bitcoin/commit/8f188ece3c82c4cf5d52a3363e7643
This is a broken link.

2021-12-12 19:44 UTC, suriyaa commented on bip-0016.mediawiki
> +These new rules should only be applied when validating transactions in blocks with timestamps >= 1333238400 (Apr 1 2012) <ref>[https://github.com/bitcoin/bitcoin/commit/8f188ece3c82c4cf5d52a3363e7643
@katesalazar Should I remove them all?

2021-12-15 15:14 UTC, suriyaa commented
See also related pull request #1250.

2021-12-15 21:23 UTC, luke-jr commented
I don't see the need to replace with https everywhere. It's not like the links are privacy or security sensitive...

Also prefer not redirecting blockexplorer.com links to blockchain.com.

But ultimately the authors of each BIP will have to make the call...

2021-12-15 23:05 UTC, kallewoof commented
I see this as bloat, personally. I also think we need to keep PRs to per-BIP unless there's a group of them (e.g. the taproot BIPs).

2021-12-16 10:31 UTC, katesalazar commented
In 4b795029bf4e I think there are no broken links left to be _fixed_.

2024-04-26 20:10 UTC, murchandamus commented
I’m closing this PR as it has multiple merge conflicts and has been inactive for almost three years, the replacement of `http` with `https` seems unnecessary, and the broken links appear to have been fixed via archive links or seem to be working again.

I would suggest that any outstanding issues are addressed with new PRs that focus only on a single document each.

2024-04-26 20:10 UTC, closed without merging