Add BIP39 implementation reference
bitcoin/bips pull request #1340
Opened 2022-07-02 10:14 UTC by hujiulong

Add a reference to the JS implementation

2022-07-02 18:29 UTC, rezaeghba01 requested changes

2022-07-02 18:29 UTC, rezaeghba01 commented on bip-0039.mediawiki
> +* https://github.com/hujiulong/web-bip39
```suggestion
* https://github.com/hujiulong/web-bip39
```

2022-07-03 21:22 UTC, Yuttana12wr commented on bip-0039.mediawiki
> +* https://github.com/hujiulong/web-bip39
2

2022-07-25 21:26 UTC, luke-jr commented
@slush0 @prusnak @voisine @ebfull

2022-07-25 22:06 UTC, prusnak commented
ACK

2022-07-25 22:49 UTC, merged