bip 2: allow markdown
bitcoin/bips pull request #1504
Opened 2023-10-11 02:01 UTC by achow101

BIP authors should be allowed to write their BIPs in Markdown. The MediaWiki syntax that GitHub uses appears to be entirely undocumented (it does not always match mediawiki's documentation) which makes writing complex BIPs rather difficult. Markdown is much simpler and more concise.

2023-10-11 04:56 UTC, kallewoof commented
I think this is an acceptable amendment. @luke-jr

2023-10-16 23:25 UTC, Roasbeef commented
Omg, this would be amazing! 

Mediawiki just feels so cumbersome compared to markdown.

2023-10-16 23:57 UTC, spedroza11 commented
My problem is not fixed

On Tue, 17 Oct 2023, 9:56 am Olaoluwa Osuntokun, ***@***.***>
wrote:

> Omg, this would be amazing!
>
> Mediawiki just feels so cumbersome compared to markdown.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bips/pull/1504#issuecomment-1765419037>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDJKCKDJFFNNK7TOMKKSZPDX7W7EDAVCNFSM6AAAAAA53HKQ6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRVGQYTSMBTG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-10-17 06:40 UTC, guggero approved these changes

2023-10-17 16:42 UTC, katesalazar requested changes
Gonna guess this is missing changing `buildtable` around this line: https://github.com/bitcoin/bips/blob/e918b50731397872ad2922a1b08a5a4cd1d6d546/scripts/buildtable.pl#L98

What's the workflow of the bitcoin.it webmaster once this is merged? Would your merge this if a compiler is needed and missing and no workaround is suggested? See: https://en.bitcoin.it/wiki/Category:BIP

Concept ACK

2023-10-25 00:35 UTC, luke-jr commented
BIP 1 supported markdown, but it was removed in BIP 2. I forget why - maybe simply lack of real-world usage?

Markdown does certainly seem more popular than mediawiki format these days.

Amending BIP 2 seems like an unclear proposition, however. First, someone needs to establish that there's some kind of consensus from participants, and secondly that amending Final BIPs isn't technically correct.

2023-10-25 15:23 UTC, katesalazar commented
Hello, throwing a bunch of questions in the air

> BIP 1 supported markdown, but it was removed in BIP 2. I forget why - maybe simply lack of real-world usage?

Note (from Wikipedia) "The initial description of Markdown[[10]](https://en.wikipedia.org/wiki/Markdown#cite_note-10) contained ambiguities and raised unanswered questions, causing implementations to both intentionally and accidentally diverge from the original version. This was addressed in 2014 when long-standing Markdown contributors released [CommonMark](https://en.wikipedia.org/wiki/Markdown#Standardization), an unambiguous specification and test suite for Markdown.[[11]](https://en.wikipedia.org/wiki/Markdown#cite_note-FutureOfMarkdown-11)".

> Markdown does certainly seem more popular than mediawiki format these days.

Do you mean which flavor?

> Amending BIP 2 seems like an unclear proposition, however. First, someone needs to establish that there's some kind of consensus from participants, and secondly that amending Final BIPs isn't technically correct.

[Are BIP Comments abandoned?][0] Any other point in discussion about BIP 2? Does it make sense to replace BIP 2 with new process?

[0]: https://bitcoin.stackexchange.com/a/119375/126793

2023-12-11 04:18 UTC, kallewoof commented
@ajtowns points out that the BIP isn't final, so amending it with a minor change like the suggested one seems reasonable.

Unless there is active opposition towards this, I propose this is merged.

2023-12-17 16:10 UTC, darosior commented
Concept ACK.

2023-12-18 06:14 UTC, merged

2024-04-23 21:27 UTC, katesalazar commented
wut
does this mean, first BIP written in Markdown has to ship the necessary changes in buildtable.pl?
can we do the things in the correct order

2024-04-29 13:32 UTC, murchandamus commented
Does https://github.com/bitcoin/bips/pull/1577 address your concern, @katesalazar?