64bit arithetmic op codes
bitcoin/bips pull request #1538
Opened 2024-01-10 20:44 UTC by Christewart

This BIP describes a soft fork to add 64 bit arithmetic op codes to bitcoin

2024-01-17 16:54 UTC, EthanHeilman commented
Why not push the overflow amount and the result back on the stack?

Rather than $2^{64}-1 + 3 = \mbox{FALSE}$, do  $2^{64}-1 + 3 = 2, 1$. Where $2 = 2^{64}-1 + 3 \mod 2^{64}$ is the result and 1 is the overflow.

This would simply doing 256-bit math from 64-bit stack elements and I don't see any downsides for 64-bit operations.

2024-05-01 19:28 UTC, murchandamus requested changes
I just did a light first pass. I noticed that this document may be missing a _Rationale_ Section that describes design decisions, alternate approaches, and related work, and a _Backwards Compatibility_ section.

You may want to add the "Post-History" header to the preamble to link to discussions of this proposal on the mailing list or forums.

2024-05-01 19:28 UTC, murchandamus commented on bip-0364.mediawiki
> +  Comments-URI: https://github.com/bitcoin/bips/wiki/Comments:BIP-0364
Please refrain from issuing your own BIP numbers.

2024-05-01 19:28 UTC, murchandamus commented on bip-0364.mediawiki
> +  Title: 64 bit arithmetic operations
Maybe: 

```suggestion
  Title: 64-bit arithmetic operations
```

2024-11-14 20:47 UTC, murchandamus commented
Hey @Christewart, are you still working on this?

2024-11-14 22:49 UTC, Christewart commented
> Hey @Christewart, are you still working on this?

Yep i'm going to give it another go. I'll update soon.

2025-02-03 15:07 UTC, EthanHeilman commented on bip-0364.mediawiki
> +This BIP also expands supported precision for valid operands from `-2^31 +1` to `2^31 -1` to `-2^63 +1...2^63 -1`.
I want to make sure I understand, this isn't proposing new opcodes that handle 64-bit arithmetic is it redefining the existing opcodes. Is that correct? It's probably on your TODO list, but what is the mechanism you are using to make this a softfork? Script versioning?

In the future we may wish to increase the supported precision again. What about adding a precision commitment to make soft-forking precision upgrades easier? For instance `OP_PUSH x, OP_PRECIS`, if x >64 then `P_PUSH x OP_PRECIS` is an OP_SUCCESSx. Then if we soft precision to 128 bits, `OP_PUSH x, OP_PRECIS` becomes a NOP.

2025-02-03 22:48 UTC, Christewart commented on bip-0364.mediawiki
> +This BIP also expands supported precision for valid operands from `-2^31 +1` to `2^31 -1` to `-2^63 +1...2^63 -1`.
Hi Ethan thanks for your continued interest in this topic.

>I want to make sure I understand, this isn't proposing new opcodes that handle 64-bit arithmetic is it redefining the existing opcodes. Is that correct?

:+1:

>It's probably on your TODO list, but what is the mechanism you are using to make this a softfork? Script versioning?

My latest thinking for the upgrade mechanism is allocating a new tap leaf version to indicate the precision of arithmetic operations for Script. This was suggested by @sipa [here](https://delvingbitcoin.org/t/64-bit-arithmetic-soft-fork/397/8?u=chris_stewart_5). [You can read about how this works on delving bitcoin](https://delvingbitcoin.org/t/deploying-new-taproot-leaf-versions/406) and see my implementation of it [here](https://github.com/Christewart/bitcoin/blob/20fe67b5e4f2db7326ba5b8771c4516a7010861e/src/script/interpreter.cpp#L2019) inside the bitcoin c++ code base.

I personally think this makes Scripts easier to reason about as the leaf version indicates the precision of _all_ numeric operations. If we want to increase precision again in the future, we can allocate a new leaf version and extend the underlying precision of CScriptNum and expose that functionality as i've done here

https://github.com/Christewart/bitcoin/blob/20fe67b5e4f2db7326ba5b8771c4516a7010861e/src/script/interpreter.cpp#L257


>In the future we may wish to increase the supported precision again. What about adding a precision commitment to make soft-forking precision upgrades easier?

Committing to arbitrary precision seems hard, but i think this BIP lays the groundwork for extending precision in the future by making the precision of arithmetic operations extendable in future soft forks as required by new op codes.

I pushed to this branch staged changes in a haphazard state, apologies. I'm working on a [BIP currently to disallow 64 byte transactions in the bitcoin blockchain](https://github.com/Christewart/bips/blob/2024-12-20-64bytetxs/bip-XXXX.mediawiki) as I think that is more likely to be widely accepted by the community, and then will be coming back to this work.

2025-02-06 18:57 UTC, murchandamus commented
Hi @Christewart, it’s my understanding that this document is currently not ready for BIP Editor review, so I have labeled the pull request as Draft. Please let us know when you would like us to take a look by returning it to "Ready for Review" when it has been updated.

2025-02-07 01:13 UTC, Roasbeef commented on bip-0364.mediawiki
> +class CScriptNum
Big thumbs down at the idea of just pasting a blob of C++ code vs actually specifying the semantics of the new op codes.

2025-03-02 21:27 UTC, Christewart commented
I'm closing this PR for now as the proposals I have in my differentiate materially from this original PR.

I envision having 2 BIPs in the future to hopefully make this proposal more consumable.

1. This BIP would expand the arithmetic operations precision from `-2^31 +1` to `2^31 -1` to `-2^63 +1...2^63 -1`. This propsal _may_ also redefine behavior in arithmetic operations such as overflow handling, supporting signed vs unsigned numbers, and potentially number encoding.
2. Re-enabling opcodes. This BIP would build on the first BIP and re-enable a set of opcodes based on the foundation laid in the first BIP.

Hopefully if we ever decide to expand precision again in the future, we can heavily rely on (1) to lay the groundwork for safe precision expansion in future soft forks.

If you are interested in working on either of these with me, please reach out on delving, twitter, irc, email etc.

2025-03-02 21:27 UTC, closed without merging