Add .NET standard bip39 implementation
bitcoin/bips pull request #840
Opened 2019-09-08 23:34 UTC by graingert

2019-09-19 21:36 UTC, luke-jr commented
@slush0 @prusnak @voisine @ebfull

2022-01-25 14:01 UTC, k6xiao commented
没有 php 的实现，而且 64 位私钥只能导出24 位助记词，有的人导出了 12 位，是怎么做到的？

2022-01-25 14:16 UTC, prusnak commented
> 为什么没有php的实现，而且64位私钥导只能导出24位助记词，有的人导出12位，是怎么做到的？

* https://github.com/Bit-Wasp/bitcoin-lib-php/blob/master/src/BIP39/BIP39.php
* https://github.com/furqansiddiqui/bip39-mnemonic-php/blob/master/src/BIP39.php

2022-01-25 14:16 UTC, prusnak commented
> @slush0 @prusnak @voisine @ebfull

ACK

2022-01-25 14:31 UTC, k6xiao commented
> > 为什么没有php的实现，而且64位私钥导只能导出24位助记词，有的人导出12位，是怎么做到的？
> 
> * https://github.com/Bit-Wasp/bitcoin-lib-php/blob/master/src/BIP39/BIP39.php
> * https://github.com/furqansiddiqui/bip39-mnemonic-php/blob/master/src/BIP39.php

我使用了这个，他不能让64位私钥导出12个助记词
https://github.com/furqansiddiqui/bip39-mnemonic-php/blob/master/src/BIP39.php

2022-01-30 03:01 UTC, augustoproiete requested changes

2022-01-30 03:01 UTC, augustoproiete commented on bip-0039.mediawiki
> +* https://www.nuget.org/packages/dotnetstandard-bip39/
```suggestion
* https://github.com/elucidsoft/dotnetstandard-bip39
```

Instead if a link to the NuGet package (binary files, no source code), add a link to the GitHub repo where the implementation is.

2022-05-05 14:48 UTC, merged